# Popular tickers: {symbol: company_name}
# .TO suffix = Toronto Stock Exchange (prices in CAD)
# No suffix = US exchange (prices in USD)

POPULAR_TICKERS: dict[str, str] = {
    # ── US Mega Cap ────────────────────────────────────────────────────────────
    "AAPL":   "Apple Inc.",
    "MSFT":   "Microsoft Corp.",
    "NVDA":   "NVIDIA Corp.",
    "GOOGL":  "Alphabet Inc. (Class A)",
    "GOOG":   "Alphabet Inc. (Class C)",
    "AMZN":   "Amazon.com Inc.",
    "META":   "Meta Platforms Inc.",
    "TSLA":   "Tesla Inc.",
    "BRK.B":  "Berkshire Hathaway (Class B)",
    "LLY":    "Eli Lilly & Co.",
    "V":      "Visa Inc.",
    "JPM":    "JPMorgan Chase & Co.",
    "XOM":    "Exxon Mobil Corp.",
    "UNH":    "UnitedHealth Group Inc.",
    "MA":     "Mastercard Inc.",
    "JNJ":    "Johnson & Johnson",
    "AVGO":   "Broadcom Inc.",
    "HD":     "The Home Depot Inc.",
    "PG":     "Procter & Gamble Co.",
    "MRK":    "Merck & Co.",
    "COST":   "Costco Wholesale Corp.",
    "ABBV":   "AbbVie Inc.",
    "CVX":    "Chevron Corp.",
    "CRM":    "Salesforce Inc.",
    "AMD":    "Advanced Micro Devices Inc.",
    "NFLX":   "Netflix Inc.",
    "KO":     "Coca-Cola Co.",
    "BAC":    "Bank of America Corp.",
    "PEP":    "PepsiCo Inc.",
    "WMT":    "Walmart Inc.",
    "DIS":    "Walt Disney Co.",
    "CSCO":   "Cisco Systems Inc.",
    "ADBE":   "Adobe Inc.",
    "ORCL":   "Oracle Corp.",
    "MCD":    "McDonald's Corp.",
    "QCOM":   "Qualcomm Inc.",
    "IBM":    "IBM Corp.",
    "GE":     "GE Aerospace",
    "CAT":    "Caterpillar Inc.",
    "AMAT":   "Applied Materials Inc.",
    "TXN":    "Texas Instruments Inc.",
    "INTU":   "Intuit Inc.",
    "NOW":    "ServiceNow Inc.",
    "AMGN":   "Amgen Inc.",
    "GS":     "Goldman Sachs Group",
    "MS":     "Morgan Stanley",
    "BKNG":   "Booking Holdings Inc.",
    "ISRG":   "Intuitive Surgical Inc.",
    "UBER":   "Uber Technologies Inc.",
    "PYPL":   "PayPal Holdings Inc.",
    "PLTR":   "Palantir Technologies Inc.",
    "SNOW":   "Snowflake Inc.",
    "COIN":   "Coinbase Global Inc.",
    "SQ":     "Block Inc.",
    "SPOT":   "Spotify Technology SA",
    "SHOP":   "Shopify Inc. (NYSE)",
    "MRNA":   "Moderna Inc.",
    "PFE":    "Pfizer Inc.",
    "NKE":    "Nike Inc.",
    "BA":     "Boeing Co.",
    "HON":    "Honeywell International Inc.",
    "NEE":    "NextEra Energy Inc.",
    "INTC":   "Intel Corp.",
    "MU":     "Micron Technology Inc.",
    "LRCX":   "Lam Research Corp.",
    "KLAC":   "KLA Corp.",
    "MRVL":   "Marvell Technology Inc.",
    "PANW":   "Palo Alto Networks Inc.",
    "CRWD":   "CrowdStrike Holdings Inc.",
    "MELI":   "MercadoLibre Inc.",
    "ABNB":   "Airbnb Inc.",
    "DKNG":   "DraftKings Inc.",
    "RIVN":   "Rivian Automotive Inc.",
    "NIO":    "NIO Inc.",
    "BABA":   "Alibaba Group Holding ADR",
    "TSM":    "Taiwan Semiconductor ADR",
    "ASML":   "ASML Holding ADR",
    "NVO":    "Novo Nordisk ADR",
    "SMCI":   "Super Micro Computer Inc.",
    "ARM":    "Arm Holdings PLC",
    "DELL":   "Dell Technologies Inc.",
    "HPQ":    "HP Inc.",
    "WDC":    "Western Digital Corp.",
    "ON":     "ON Semiconductor Corp.",
    "MPWR":   "Monolithic Power Systems Inc.",
    "SCHW":   "Charles Schwab Corp.",
    "SPGI":   "S&P Global Inc.",
    "REGN":   "Regeneron Pharmaceuticals",
    "VRTX":   "Vertex Pharmaceuticals",
    "ZTS":    "Zoetis Inc.",
    "SYK":    "Stryker Corp.",
    "MDT":    "Medtronic PLC",
    "GILD":   "Gilead Sciences Inc.",
    "CI":     "Cigna Group",
    "HUM":    "Humana Inc.",
    "AXP":    "American Express Co.",
    "DE":     "Deere & Co.",
    "LIN":    "Linde PLC",
    # ── US ETFs ────────────────────────────────────────────────────────────────
    "SPY":    "SPDR S&P 500 ETF Trust",
    "QQQ":    "Invesco QQQ Trust (Nasdaq 100)",
    "VTI":    "Vanguard Total Stock Market ETF",
    "VOO":    "Vanguard S&P 500 ETF",
    "IWM":    "iShares Russell 2000 ETF",
    "GLD":    "SPDR Gold Shares ETF",
    "SLV":    "iShares Silver Trust ETF",
    "TLT":    "iShares 20+ Year Treasury Bond ETF",
    "XLK":    "Technology Select Sector SPDR ETF",
    "XLF":    "Financial Select Sector SPDR ETF",
    "XLE":    "Energy Select Sector SPDR ETF",
    "XLV":    "Health Care Select Sector SPDR ETF",
    "ARKK":   "ARK Innovation ETF",
    "VGT":    "Vanguard Information Technology ETF",
    "SOXX":   "iShares Semiconductor ETF",
    "VNQ":    "Vanguard Real Estate ETF",
    "DIA":    "SPDR Dow Jones Industrial Average ETF",
    "IVV":    "iShares Core S&P 500 ETF",
    "AGG":    "iShares Core U.S. Aggregate Bond ETF",
    "BND":    "Vanguard Total Bond Market ETF",
    "VEA":    "Vanguard FTSE Developed Markets ETF",
    "VWO":    "Vanguard FTSE Emerging Markets ETF",
    "EFA":    "iShares MSCI EAFE ETF",
    "EEM":    "iShares MSCI Emerging Markets ETF",
    "SCHD":   "Schwab US Dividend Equity ETF",
    "JEPI":   "JPMorgan Equity Premium Income ETF",
    "JEPQ":   "JPMorgan Nasdaq Equity Premium Income ETF",
    # ── Canadian Stocks (TSX) ──────────────────────────────────────────────────
    "SHOP.TO":    "Shopify Inc.",
    "RY.TO":      "Royal Bank of Canada",
    "TD.TO":      "Toronto-Dominion Bank",
    "BNS.TO":     "Bank of Nova Scotia",
    "BMO.TO":     "Bank of Montreal",
    "CM.TO":      "CIBC",
    "NA.TO":      "National Bank of Canada",
    "CNR.TO":     "Canadian National Railway",
    "CP.TO":      "Canadian Pacific Kansas City",
    "ENB.TO":     "Enbridge Inc.",
    "TRP.TO":     "TC Energy Corp.",
    "SU.TO":      "Suncor Energy Inc.",
    "CNQ.TO":     "Canadian Natural Resources",
    "CVE.TO":     "Cenovus Energy Inc.",
    "ABX.TO":     "Barrick Gold Corp.",
    "AEM.TO":     "Agnico Eagle Mines",
    "WPM.TO":     "Wheaton Precious Metals",
    "K.TO":       "Kinross Gold Corp.",
    "MFC.TO":     "Manulife Financial Corp.",
    "SLF.TO":     "Sun Life Financial Inc.",
    "GWO.TO":     "Great-West Lifeco Inc.",
    "BCE.TO":     "BCE Inc. (Bell Canada)",
    "T.TO":       "TELUS Corp.",
    "RCI.B.TO":   "Rogers Communications",
    "MG.TO":      "Magna International Inc.",
    "CCO.TO":     "Cameco Corp.",
    "BAM.TO":     "Brookfield Asset Management",
    "BN.TO":      "Brookfield Corp.",
    "BIP.UN.TO":  "Brookfield Infrastructure Partners",
    "BEP.UN.TO":  "Brookfield Renewable Partners",
    "ATD.TO":     "Alimentation Couche-Tard",
    "L.TO":       "Loblaw Companies Ltd.",
    "DOL.TO":     "Dollarama Inc.",
    "TFII.TO":    "TFI International Inc.",
    "WCN.TO":     "Waste Connections Inc.",
    "CSU.TO":     "Constellation Software Inc.",
    "KXS.TO":     "Kinaxis Inc.",
    "OTEX.TO":    "OpenText Corp.",
    "AC.TO":      "Air Canada",
    "CAR.UN.TO":  "Canadian Apartment REIT",
    "REI.UN.TO":  "RioCan REIT",
    "H.TO":       "Hydro One Ltd.",
    "FTS.TO":     "Fortis Inc.",
    "EMA.TO":     "Emera Inc.",
    "POW.TO":     "Power Corp of Canada",
    "IMO.TO":     "Imperial Oil Ltd.",
    # ── Canadian ETFs ──────────────────────────────────────────────────────────
    "XIU.TO":     "iShares S&P/TSX 60 ETF",
    "XIC.TO":     "iShares Core S&P/TSX Composite ETF",
    "ZSP.TO":     "BMO S&P 500 ETF (CAD)",
    "VFV.TO":     "Vanguard S&P 500 ETF (CAD)",
    "XSP.TO":     "iShares S&P 500 ETF (CAD Hedged)",
    "HXS.TO":     "Horizons S&P 500 ETF",
    "XUS.TO":     "iShares Core S&P 500 ETF (CAD Unhedged)",
    "ZQQ.TO":     "BMO NASDAQ 100 ETF",
    "XQQ.TO":     "iShares NASDAQ 100 ETF (CAD Hedged)",
    "VUN.TO":     "Vanguard US Total Market ETF",
    "XAW.TO":     "iShares Core MSCI All Country World ex Canada",
    "VXC.TO":     "Vanguard FTSE Global All Cap ex Canada",
    "XGRO.TO":    "iShares Core Growth ETF Portfolio",
    "XBAL.TO":    "iShares Core Balanced ETF Portfolio",
    "XEQT.TO":    "iShares Core Equity ETF Portfolio",
    "VGRO.TO":    "Vanguard Growth ETF Portfolio",
    "VBAL.TO":    "Vanguard Balanced ETF Portfolio",
    "VEQT.TO":    "Vanguard All-Equity ETF Portfolio",
    "ZGRO.TO":    "BMO Growth ETF",
    "ZBAL.TO":    "BMO Balanced ETF",
    "ZAG.TO":     "BMO Aggregate Bond ETF",
    "XBB.TO":     "iShares Core Canadian Universe Bond ETF",
    "ZEB.TO":     "BMO Equal Weight Banks ETF",
    "ZRE.TO":     "BMO Equal Weight REITs ETF",
    "HXT.TO":     "Horizons S&P/TSX 60 ETF",
}


def ticker_currency(ticker: str) -> str:
    """Return 'CAD' for .TO tickers, 'USD' for all others."""
    return "CAD" if ticker.upper().endswith(".TO") else "USD"


def search_tickers(query: str, max_results: int = 12) -> list[tuple[str, str]]:
    """
    Return [(ticker, name), ...] filtered by query string.
    Matches against ticker symbol and company name (case-insensitive).
    """
    q = query.upper().strip()
    if not q:
        return []
    results = []
    for ticker, name in POPULAR_TICKERS.items():
        if q in ticker or q in name.upper():
            results.append((ticker, name))
        if len(results) >= max_results:
            break
    return results


# Formatted options list for st.selectbox — "TICKER — Company Name"
TICKER_OPTIONS: list[str] = [
    f"{ticker} — {name}" for ticker, name in POPULAR_TICKERS.items()
]


def parse_ticker_option(option: str) -> str:
    """Extract ticker from 'TICKER — Company Name' string."""
    return option.split(" — ")[0].strip()
